pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {

    stage ('Prepare destination host') {
      steps {
        sh '''
          ssh -T centos@192.168.231.144 << ENDSSH
          sudo rm -rf /home/centos/deploy
          sudo sleep 2
          mkdir /home/centos/deploy/
          sudo chmod -R 775 /home/centos/deploy
          cd /home/centos/deploy/
          sudo dnf install npm -y
          sudo npm install
ENDSSH
      '''
      }
    }

    stage('checkout + application scp') {
      steps {
        git 'https://github.com/bhimra/deploy-rollback-pipeline.git'
        sh 'sudo chmod -R 775 /var/lib/jenkins/workspace/deploy-rollback-pipeline/'
        sh 'scp /var/lib/jenkins/workspace/deploy-rollback-pipeline/index.js centos@192.168.231.144:/home/centos/deploy'
      }
    }

    stage ('Verify node service') {
      steps {
        sh '''
          ssh -t -t  centos@192.168.231.144 'bash -s << 'ENDSSH'
          whoami
          if [[ Z=$(sudo ps aux | grep -i [n]ode | awk 'NR==1' | gawk {'print $2'}) ]];
          then
              sudo kill -9 $Z
              echo "node service stop successfully."
              sudo pkill node
              exit 0
          else
              echo "node service failed"
          fi
ENDSSH'
      '''
      }
    }
    
    stage('ArchiveArtifacts'){
            steps{
                archiveArtifacts artifacts: '**', followSymlinks: false
            }
        }
    
    stage ('Start the node service') {
      steps {
        sh '''
        set -x
        ssh centos@192.168.231.144 "
                    sudo chmod -R 775 /home/centos/deploy/
                    node /home/centos/deploy/index.js > /dev/null 2>&1 <&- & "
        sudo sleep 5                    
        X=$(curl -k  -o /dev/null -s -w %{http_code} http://192.168.231.144:3000)
        if [ $X -eq 200 ];
            then
                echo -e 'web site is running'
            else
                echo -e 'web site is down' 
        fi '''
      }
    }
    
   post {
        // Clean after build
        always {
            cleanWs()
        }
     }
  }
}
