pipeline {
  agent any
    
  tools {nodejs "node"}
    
 stages {
   
    stage('Copy Artifact') {
      steps {
            copyArtifacts filter: '**', fingerprintArtifacts: true, projectName: 'deploy-rollback-pipeline', selector: specific('$BUILD_NUMBER')
        }
    }

    stage ('Verify node service') {
      steps {
        sh '''
          ssh -t -t  centos@192.168.231.144 'bash -s << 'ENDSSH'
          if [[ Z=$(sudo ps aux | grep -i [n]ode | awk 'NR==1' | gawk {'print $2'}) ]];
          then
              sudo kill -9 $Z
              sudo pkill node
              echo "node service stop successfully......................................."
          else
              echo "node service failed.................................................."
          fi
ENDSSH'
      '''
      }
    }
    
    stage ('Start the node service') {
      steps {
        sh '''
        sh 'pwd'
        sh 'scp index.js centos@192.168.231.144:/home/centos/deploy' 
        ssh centos@192.168.231.144"
                    cd /home/centos/deploy
                    sudo chmod +x *
                    node index.js > /dev/null 2>&1 <&- &"
        sudo sleep 5            
        X=$(curl -k  -o /dev/null -s -w %{http_code} http://192.168.231.144:3000)
        if [ $X -eq 200 ];
            then
                echo -e 'web site is running'
            else
                echo -e 'web site is down' 
        fi '''
      }
    }
  }
} 
